//
//  ConstsForSend.swift
//  Drift
//
//  Created by Ignat Urbanovich on 3.11.21.
//

import Foundation

let USER_TYPE_ORDINARY = "ORDINARY"

//FROM CLIENT TO SERVER

//system commands 0-99
let CLIENT_CONST_NULL = 0
let CLIENT_CONST_END_SESSION = 999

//work with USER - 100-199
let CLIENT_CONST_CHECK_USER = 101
let CLIENT_CONST_SIGN_USER = 102
let CLIENT_CONST_GET_FULL_USER = 103

//work with CUP - 200-299
let CLIENT_CONST_GET_CUPS = 201
let CLIENT_CONST_GET_CUPS_FOR_USER = 202
let CLIENT_CONST_GET_ONE_CUP_INFO = 203
let CLIENT_CONST_SAVE_CUP = 204

//work with STAGE - 300-399
let CLIENT_CONST_GET_STAGE_GRID = 301
let CLIENT_CONST_GET_ONE_STAGE_INFO = 302
let CLIENT_CONST_SAVE_STAGE = 303
let CLIENT_CONST_GET_STAGE_PARTICIPIANTS = 304
let CLIENT_CONST_SAVE_PARTICIPIANTS = 305;
let CLIENT_CONST_GET_STAGE_RUNS = 306;

//work with STAGE STATUSES - 320-340
let CLIENT_CONST_SET_STAGE_STATUS = 320;

let CLIENT_CONST_SET_RUN_STATUS = 340;

//work with ONLINE - 400-499
let CLIENT_CONST_GET_ONLINE = 401
let CLIENT_CONST_ADD_JUDGE_DECISION = 402

//work with JUDGES - 500-599
let CLIENT_CONST_GET_ALL_JUDGES = 501

//work with DRIVERS - 600-699
let CLIENT_CONST_GET_ALL_DRIVERS = 601
let CLIENT_CONST_SAVE_DRIVER = 602



//FROM SERVER TO CLIENT

//system command
let SERVER_CONST_NULL = 0

//work with USER - 100-199
let SERVER_CONST_USER_EXIST = 101
let SERVER_CONST_USER_SIGNED = 102
let SERVER_CONST_USER_NOT_EXIST = 103
let SERVER_CONST_USER_EXIST_CANT_SIGN = 104
let SERVER_CONST_INCORRECT_USER = 105
let SERVER_CONST_USER_OF_SESSION = 106

//work with CUP - 200-299
let SERVER_CONST_CUPS_EMPTY = 201
let SERVER_CONST_WITH_CUPS = 202
let SERVER_CONST_ERROR_CUP_SAVING = 203
let SERVER_CONST_CUP_SAVING_SUCCESS = 204
let SERVER_CONST_WITH_STAGES = 205
let SERVER_CONST_STAGES_EMPTY = 206

//work with STAGE - 300-399
let SERVER_CONST_ERROR_GETTIN_GRID = 300;
let SERVER_CONST_WITH_STAGE_GRID = 301;
let SERVER_CONST_STAGE_SAVED = 302
let SERVER_CONST_STAGE_NOT_SAVED = 303
let SERVER_CONST_NO_STAGE_PARICIPIANTS = 304;
let SERVER_CONST_WITH_STAGE_PARICIPIANTS = 305;
let SERVER_CONST_PARICIPIANTS_SAVED = 306;
let SERVER_CONST_PARICIPIANTS_NOT_SAVED = 307;
let SERVER_CONST_WITH_STAGE_RUNS = 308;
let SERVER_CONST_NO_STAGE_RUNS = 309;

let SERVER_CONST_STAGE_NEW_STATUS = 321;

let SERVER_CONST_RUN_NEW_STATUS = 341;
let SERVER_CONST_RUN_STATUS_NOT_UPDATED = 342;

//work with ONLINE - 400-499
let SERVER_CONST_NOTHING_ONLINE = 401
let SERVER_CONST_ONLINE_STAGE = 402
let SERVER_CONST_ONLINE_RUN = 403
let SERVER_CONST_ONLINE_JUDGE_DECISION = 404

//work with JUDGES - 500-599
let SERVER_CONST_WITH_JUDGES = 501
let SERVER_CONST_NO_JUDGES = 502

//work with JUDGES - 600-699
let SERVER_CONST_WITH_DRIVERS = 601
let SERVER_CONST_DRIVER_SAVED = 602;
let SERVER_CONST_DRIVER_SAVING_ERROR = 603;

